//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.11 at 09:24:49 PM EEST 
//


package org.sonar.plugins.tsql.languages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rule" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="internalKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="descriptionFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cardinality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="remediationFunction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="remediationFunctionBaseEffort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="debtRemediationFunctionCoefficient" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rule"
})
@XmlRootElement(name = "sql-rules")
public class SqlRules {

    protected List<SqlRules.Rule> rule;

    /**
     * Gets the value of the rule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SqlRules.Rule }
     * 
     * 
     */
    public List<SqlRules.Rule> getRule() {
        if (rule == null) {
            rule = new ArrayList<SqlRules.Rule>();
        }
        return this.rule;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="internalKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="descriptionFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cardinality" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="remediationFunction" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="remediationFunctionBaseEffort" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="debtRemediationFunctionCoefficient" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "key",
        "name",
        "internalKey",
        "descriptionFormat",
        "description",
        "severity",
        "cardinality",
        "status",
        "tag",
        "remediationFunction",
        "remediationFunctionBaseEffort",
        "debtRemediationFunctionCoefficient"
    })
    public static class Rule {

        @XmlElement(required = true)
        protected String key;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String internalKey;
        @XmlElement(required = true)
        protected String descriptionFormat;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected String severity;
        @XmlElement(required = true)
        protected String cardinality;
        @XmlElement(required = true)
        protected String status;
        @XmlElement(required = true)
        protected String tag;
        @XmlElement(required = true)
        protected String remediationFunction;
        @XmlElement(required = true)
        protected String remediationFunctionBaseEffort;
        @XmlElement(required = true)
        protected String debtRemediationFunctionCoefficient;

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKey(String value) {
            this.key = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the internalKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternalKey() {
            return internalKey;
        }

        /**
         * Sets the value of the internalKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternalKey(String value) {
            this.internalKey = value;
        }

        /**
         * Gets the value of the descriptionFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescriptionFormat() {
            return descriptionFormat;
        }

        /**
         * Sets the value of the descriptionFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescriptionFormat(String value) {
            this.descriptionFormat = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the severity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeverity() {
            return severity;
        }

        /**
         * Sets the value of the severity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeverity(String value) {
            this.severity = value;
        }

        /**
         * Gets the value of the cardinality property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardinality() {
            return cardinality;
        }

        /**
         * Sets the value of the cardinality property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardinality(String value) {
            this.cardinality = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the tag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTag() {
            return tag;
        }

        /**
         * Sets the value of the tag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTag(String value) {
            this.tag = value;
        }

        /**
         * Gets the value of the remediationFunction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemediationFunction() {
            return remediationFunction;
        }

        /**
         * Sets the value of the remediationFunction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemediationFunction(String value) {
            this.remediationFunction = value;
        }

        /**
         * Gets the value of the remediationFunctionBaseEffort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemediationFunctionBaseEffort() {
            return remediationFunctionBaseEffort;
        }

        /**
         * Sets the value of the remediationFunctionBaseEffort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemediationFunctionBaseEffort(String value) {
            this.remediationFunctionBaseEffort = value;
        }

        /**
         * Gets the value of the debtRemediationFunctionCoefficient property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDebtRemediationFunctionCoefficient() {
            return debtRemediationFunctionCoefficient;
        }

        /**
         * Sets the value of the debtRemediationFunctionCoefficient property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDebtRemediationFunctionCoefficient(String value) {
            this.debtRemediationFunctionCoefficient = value;
        }

    }

}
